### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by ComLock** [enonic/starter-react4xp#12]
I know both Enonic XP and some React (mostly jsx) so my thought was that it should be easy for me to start coding using the react4xp starter. Starting to read the documentation I quickly get the oppsite impression. So I give up on the documentation and look for some example/tutorial code, but there are none in the starter...

It feels like I have become a rocket scientist to make a wheel :)

**Comment by ComLock** [comment]
Just found out about the examples branch. Interesting workaround. But once I've created a project with the starter I can't switch to the branch...

**Comment by espen42** [comment]
This was as requested by @sigdestad .
