### ISSUE TITLE
react4xp as a monorepo?

### ISSUE THREAD

**Issue by realmunk** [enonic/starter-react4xp#19]
There's quite a few moving parts for react4xp, and as a developer I find it hard to get an overview of how they work together. Currently I have to spend alot of time across repos to get familiar with the setup.

To make the management and co-development of this repo easier, it may be beneficial to set it up as a monorepo managed by [lerna](https://github.com/lerna/lerna).

This will make it easier to keep the code close, see changes in unison as you develop, and update dependencies:

1.  #https://github.com/enonic/react4xp-runtime-client
2. https://github.com/enonic/react4xp-templates
3. https://github.com/enonic/react4xp-runtime-nashornpolyfills
4. https://github.com/enonic/react4xp-build-constants
5. https://github.com/enonic/react4xp-build-entriesandchunks
6. https://github.com/enonic/lib-react4xp
7. https://github.com/enonic/doc-starter-react4xp

What do you think?

**Comment by espen42** [comment]
Yep, Lerna is definitely in the pipeline (https://github.com/enonic/lib-react4xp/issues/28 -  
It's even for that exact reason I'm trying to keep all the react4xp issues in one place. :D )
