### ISSUE TITLE
Don't use hardcoded asset or service urls

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-react4xp#2]
In all html template files, hardcoded url's to assets and services are used.
This is not best practice, replace by using portal functions (either passing urls from controller, or inline in template)

**Comment by espen42** [comment]
Ok, except for `pure.html`. The whole point of that it to show how react4xp can work on services alone, no controller input as long as you know the base URL to the services. 

Not sure how to solve that (insertion of a dynamic app name) at the moment, but I'll have a look.
