### ISSUE TITLE
.es6 controllers not using portal functions

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-react4xp#4]
Again, url's are hardcoded in controllers too.

i.e.   { urls: [...dependencies.getAllUrls('SimpleGreeter'), `/_/service/${app.name}/react4xp/SimpleGreeter`] } :

Must be fixed to use proper url generation

**Comment by espen42** [comment]
As in 
```
{ urls: [
    ...dependencies.getAllUrls('SimpleGreeter'), 
    `${portal.serviceUrl({service: 'react4xp'})}/SimpleGreeter`
]}
```
?

Sure!
