### ISSUE TITLE
Use webjars instead of custom node module for react?

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-react4xp#5]
From the code.

``

To mee, this seems like the "externals" parts was made to serve the vanilla require files?
If these can be served as plain assets, why not rather use precompiled webjars? Similar to how things are done in the Babel starter?

**Comment by sigdestad** [comment]
We prefer serving assets directly over CDN's as this gives us full control and higher security. So this should be our default approach.

We whould not "confuse" developers with CDN etc in starter. This could optionally be part of the docs imho?

**Comment by espen42** [comment]
Good point. I can look into that.

**Comment by espen42** [comment]
The externals is a transpiled asset that's needed either way - the nashorn engine runs it as part of the SSR preparations (that's what makes it different from other dependency chunks: they are also run in the backend and frontend, but everything that's packed into externals becomes directly available to _other_ JS code in the client. The rest is encapsulated into the `React4xp` object).

So I guess you could argue both ways: if you use a CDN on the client side, it's a more common and recognizable pattern. And if you serve the externals asset instead, you're guaranteed isomorphism: the same code and same versions rendering on the backend and frontend.

**Comment by espen42** [comment]
Updated the examples and some of the comments and the guide. Better?

**Comment by espen42** [comment]
Related: https://github.com/enonic/lib-react4xp/issues/22 and https://github.com/enonic/lib-react4xp/issues/18
