### ISSUE TITLE
Webapp starter concept

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-react4xp#6]
I'm having trouble understanding the webapp part of the starter?

1. What is the first page served actually doing?
2. What is the "pure" page doing?

I thought the purpose of react4xp was serverside rendering on initial request, then handover to client side? It is hard to understand the current examples basically.

Suggestion: The inital page rendered should be 100% server generated with JSX, then hydrated demoing how parts of it are now client side react or something like that?

To be discussed

**Comment by espen42** [comment]
No, serverside rendering is a bonus feature IMO.

The biggest selling points of react are:

1, the fast DOM manipulation on the client side - effective enough for anything from animations and immediate/load-free substructure updates responding to user interaction, to leaving the DOM of an entire single-page webapp to be entirely handled and built in real time from nothing but a container element. 

2, JSX, the neat and pleasant templating language. 

React4xp aims to make both easy to do/use in XP. You can server-side pre-render a starting point for a react element, pure DOM which is activated by `hydrate` on the client. Or you can even skip the hydration and use the server-side JSX rendering as a pure templating language, competing with thymeleaf. But in some cases what you'd want to do is to just supply a container in the DOM from the server, and tell the client to run the component in client-side React and build the DOM into it from scratch. 

The webapp demonstrates that last use case in two different ways. 

In the first page, how to make a controller deliver the URLs for the dependencies. The "pure" page shows how react4xp can, if you need it, work with only HTML pages requesting what they need from the services (no need for a controller at all - except for serving the HTML).

So I think at least the "pure" demo is needed.

But we should probably separate them more sharply. And sure, the "impure" one could involve some initial server-side rendering, that could be nice!

**Comment by espen42** [comment]
Webapp demo in the examples branch seems buggy now? Investigate and fix.

**Comment by espen42** [comment]
Done: fe1cba0
