### ISSUE TITLE
Improved site examples needed

### ISSUE THREAD

**Issue by sigdestad** [enonic/starter-react4xp#8]
It is perfectly fine for the site example to mix use of thymeleaf and jsx, however, the JSX based examples are now hard to separate, as they all are "hello world" things.

We should improve the info per part on the output/rendering:

1. Use a clear part title
2. Nice description of how it works
3. Then something using the configuration element

NB! I don't think all the sample parts should have config.

Also, like the idea of building up with more an more complex examples.

**Comment by espen42** [comment]
Agreed.

**Comment by espen42** [comment]
Done, see the starter guide
