### ISSUE TITLE
Material UI SSR

### ISSUE THREAD

**Issue by pvmerlo** [enonic/starter-react4xp#89]
Hello, guys! Some of you have used this starter with Material UI and Tailwind CSS? Can you give me some hints on how I should configure these libs to get them working on a fresh new project?

**Comment by espen42** [comment]
Hi! I personally haven't tried this yet, and I'm not aware of anyone who has. It's in the pipeline, though: 

https://github.com/enonic/lib-react4xp/issues/104

If you beat us to it and get it working - or just got a good start going and maybe need some wrinkle-straightening tips - feel free to ask here, in that issue, or on [our forum](https://discuss.enonic.com/search?q=react4xp). Good luck!
